public class Main {
    public static void main(String[] args) {
        Graph graph = new Graph();
        Graph graph1 = new Graph();
        Graph graph2 = new Graph();


        graph.addNode("Alpha");
        graph.addNode("Beta");
        graph.addNode("Gamma");
        graph.addNode("Delta");
        graph.addNode("Epsilon");
        graph.addNode("Zeta");
        graph.addNode("Eta");
        graph.addNode("Theta");
        graph.addNode("Iota");
        graph.addNode("Kappa");
        graph.addNode("Lambda");
        graph.addNode("Mu");
        graph.addNode("Nu");
        graph.addNode("Xi");
        graph.addNode("omnicron");
        graph.addNode("Sigma");
        graph.addNode("Omega");

        graph.addEdge("Alpha", "Beta", 8);
        graph.addEdge("Alpha", "Delta", 9);
        graph.addEdge("Alpha", "Eta", 10);
        graph.addEdge("Beta", "Alpha", 8);
        graph.addEdge("Beta", "Delta", 3);
        graph.addEdge("Beta", "Gamma", 7);
        graph.addEdge("Gamma", "Beta", 7);
        graph.addEdge("Gamma", "Delta", 17);
        graph.addEdge("Gamma", "Zeta", 8);
        graph.addEdge("Delta", "Alpha", 9);
        graph.addEdge("Delta", "Beta", 3);
        graph.addEdge("Delta", "Gamma", 17);
        graph.addEdge("Delta", "Epsilon", 4);
        graph.addEdge("Delta", "Theta", 7);
        graph.addEdge("Delta", "Eta", 2);
        graph.addEdge("Eta", "Alpha", 10);
        graph.addEdge("Eta", "Delta", 2);
        graph.addEdge("Eta", "Lambda", 9);
        graph.addEdge("Lambda", "Eta", 9);
        graph.addEdge("Lambda", "Mu", 8);
        graph.addEdge("Theta", "Delta", 7);
        graph.addEdge("Theta", "Epsilon", 4);
        graph.addEdge("Theta", "Iota", 3);
        graph.addEdge("Theta", "Kappa", 9);
        graph.addEdge("Mu", "Lambda", 8);
        graph.addEdge("Mu", "Kappa", 14);
        graph.addEdge("Mu", "Xi", 8);
        graph.addEdge("Xi", "Mu", 8);
        graph.addEdge("Xi", "omnicron", 5);
        graph.addEdge("omnicron", "Xi", 5);
        graph.addEdge("omnicron", "Sigma", 9);
        graph.addEdge("omnicron", "Nu", 9);
        graph.addEdge("Nu", "omnicron", 9);
        graph.addEdge("Nu", "Kappa", 9);
        graph.addEdge("Nu", "Omega", 10);
        graph.addEdge("Omega", "Nu", 10);
        graph.addEdge("Sigma", "omnicron", 9);
        graph.addEdge("Kappa", "Theta", 9);
        graph.addEdge("Kappa", "Mu", 14);
        graph.addEdge("Kappa", "Nu", 9);
        graph.addEdge("Kappa", "Iota", 5);
        graph.addEdge("Epsilon", "Delta", 4);
        graph.addEdge("Epsilon", "Theta", 4);
        graph.addEdge("Epsilon", "Zeta", 9);
        graph.addEdge("Zeta", "Epsilon", 9);
        graph.addEdge("Zeta", "Gamma", 8);
        graph.addEdge("Zeta", "Iota", 10);
        graph.addEdge("Iota", "Zeta", 10);
        graph.addEdge("Iota", "Theta", 3);
        graph.addEdge("Iota", "Kappa", 5);

        graph.dijkstra("Alpha");
        graph.printPaths("Alpha");

        graph1.addNode("Alpha");
        graph1.addNode("Beta");
        graph1.addNode("Gamma");
        graph1.addNode("Delta");
        graph1.addNode("Epsilon");
        graph1.addNode("Zeta");
        graph1.addNode("Eta");
        graph1.addNode("Theta");
        graph1.addNode("Iota");
        graph1.addNode("Kappa");
        graph1.addNode("Lambda");
        graph1.addNode("Mu");
        graph1.addNode("Nu");
        graph1.addNode("Xi");
        graph1.addNode("Omnicron");
        graph1.addNode("Sigma");
        graph1.addNode("Omega");

        graph1.addEdge("Alpha", "Beta", 8);
        graph1.addEdge("Alpha", "Delta", 9);
        graph1.addEdge("Alpha", "Eta", 10);
        graph1.addEdge("Beta", "Alpha", 8);
        graph1.addEdge("Beta", "Delta", 3);
        graph1.addEdge("Beta", "Gamma", 7);
        graph1.addEdge("Gamma", "Beta", 7);
        graph1.addEdge("Gamma", "Delta", 17);
        graph1.addEdge("Gamma", "Zeta", 8);
        graph1.addEdge("Delta", "Alpha", 9);
        graph1.addEdge("Delta", "Beta", 3);
        graph1.addEdge("Delta", "Gamma", 17);
        graph1.addEdge("Delta", "Epsilon", 4);
        graph1.addEdge("Delta", "Theta", 7);
        graph1.addEdge("Delta", "Eta", 2);
        graph1.addEdge("Eta", "Alpha", 10);
        graph1.addEdge("Eta", "Delta", 2);
        graph1.addEdge("Eta", "Lambda", 9);
        graph1.addEdge("Lambda", "Eta", 9);
        graph1.addEdge("Lambda", "Mu", 8);
        graph1.addEdge("Lambda", "Xi", 7);
        graph1.addEdge("Lambda", "Theta", 14);
        graph1.addEdge("Theta", "Delta", 7);
        graph1.addEdge("Theta", "Epsilon", 5);
        graph1.addEdge("Theta", "Mu", 4);
        graph1.addEdge("Theta", "Iota", 4);
        graph1.addEdge("Theta", "Kappa", 3);
        graph1.addEdge("Theta", "Lambda", 14);
        graph1.addEdge("Mu", "Lambda", 8);
        graph1.addEdge("Mu", "Kappa", 9);
        graph1.addEdge("Mu", "Xi", 10);
        graph1.addEdge("Mu", "Omnicron", 8);
        graph1.addEdge("Mu", "Theta", 4);
        graph1.addEdge("Mu", "Nu", 14);
        graph1.addEdge("Xi", "Mu", 10);
        graph1.addEdge("Xi", "Lambda",  7);
        graph1.addEdge("Xi", "Sigma", 9);
        graph1.addEdge("Omnicron", "Mu", 8);
        graph1.addEdge("Omnicron", "Sigma", 9);
        graph1.addEdge("Omnicron", "Nu", 7);
        graph1.addEdge("omnicron", "Omega", 10);
        graph1.addEdge("Nu", "omnicron", 7);
        graph1.addEdge("Nu", "Kappa", 7);
        graph1.addEdge("Nu", "Omega", 9);
        graph1.addEdge("Nu", "Iota", 9);
        graph1.addEdge("Nu", "Mu", 14);
        graph1.addEdge("Omega", "Nu", 9);
        graph1.addEdge("Omega", "Omnicron", 10);
        graph1.addEdge("Sigma", "omnicron", 9);
        graph1.addEdge("Sigma", "Xi", 5);
        graph1.addEdge("Kappa", "Theta", 3);
        graph1.addEdge("Kappa", "Mu", 9);
        graph1.addEdge("Kappa", "Nu", 7);
        graph1.addEdge("Kappa", "Iota", 5);
        graph1.addEdge("Epsilon", "Delta", 4);
        graph1.addEdge("Epsilon", "Theta", 5);
        graph1.addEdge("Epsilon", "Zeta", 9);
        graph1.addEdge("Zeta", "Epsilon", 9);
        graph1.addEdge("Zeta", "Gamma", 8);
        graph1.addEdge("Zeta", "Iota", 10);
        graph1.addEdge("Iota", "Zeta", 10);
        graph1.addEdge("Iota", "Theta", 4);
        graph1.addEdge("Iota", "Kappa", 5);
        graph1.addEdge("Iota", "Theta", 4);

        System.out.println("\n================================================");
        graph1.dijkstra("Theta");
        graph1.printPaths("Theta");

        graph2.addNode("Alpha");
        graph2.addNode("Beta");
        graph2.addNode("Gamma");
        graph2.addNode("Delta");
        graph2.addNode("Epsilon");
        graph2.addNode("Zeta");
        graph2.addNode("Eta");
        graph2.addNode("Theta");
        graph2.addNode("Iota");
        graph2.addNode("Kappa");
        graph2.addNode("Lambda");
        graph2.addNode("Mu");
        graph2.addNode("Nu");
        graph2.addNode("Xi");
        graph2.addNode("Omnicron");
        graph2.addNode("Sigma");
        graph2.addNode("Omega");

        graph2.addEdge("Alpha", "Beta", 8);
        graph2.addEdge("Alpha", "Delta", 9);
        graph2.addEdge("Alpha", "Eta", 10);
        graph2.addEdge("Beta", "Alpha", 8);
        graph2.addEdge("Beta", "Delta", 3);
        graph2.addEdge("Beta", "Gamma", 7);
        graph2.addEdge("Gamma", "Beta", 7);
        graph2.addEdge("Gamma", "Delta", 17);
        graph2.addEdge("Gamma", "Zeta", 8);
        graph2.addEdge("Delta", "Alpha", 9);
        graph2.addEdge("Delta", "Beta", 3);
        graph2.addEdge("Delta", "Gamma", 17);
        graph2.addEdge("Delta", "Epsilon", 4);
        graph2.addEdge("Delta", "Theta", 7);
        graph2.addEdge("Delta", "Eta", 2);
        graph2.addEdge("Eta", "Alpha", 10);
        graph2.addEdge("Eta", "Delta", 2);
        graph2.addEdge("Eta", "Lambda", 9);
        graph2.addEdge("Lambda", "Eta", 9);
        graph2.addEdge("Lambda", "Mu", 8);
        graph2.addEdge("Lambda", "Xi", 7);
        graph2.addEdge("Lambda", "Theta", 14);
        graph2.addEdge("Theta", "Delta", 7);
        graph2.addEdge("Theta", "Epsilon", 5);
        graph2.addEdge("Theta", "Mu", 4);
        graph2.addEdge("Theta", "Iota", 4);
        graph2.addEdge("Theta", "Kappa", 3);
        graph2.addEdge("Theta", "Lambda", 14);
        graph2.addEdge("Mu", "Lambda", 8);
        graph2.addEdge("Mu", "Kappa", 9);
        graph2.addEdge("Mu", "Xi", 10);
        graph2.addEdge("Mu", "Omnicron", 8);
        graph2.addEdge("Mu", "Theta", 4);
        graph2.addEdge("Mu", "Nu", 14);
        graph2.addEdge("Xi", "Mu", 10);
        graph2.addEdge("Xi", "Lambda",  7);
        graph2.addEdge("Xi", "Sigma", 5);
        graph2.addEdge("Omnicron", "Mu", 8);
        graph2.addEdge("Omnicron", "Sigma", 9);
        graph2.addEdge("Omnicron", "Nu", 5);
        graph2.addEdge("omnicron", "Omega", 10);
        graph2.addEdge("Nu", "omnicron", 5);
        graph2.addEdge("Nu", "Kappa", 7);
        graph2.addEdge("Nu", "Omega", 9);
        graph2.addEdge("Nu", "Iota", 9);
        graph2.addEdge("Nu", "Mu", 14);
        graph2.addEdge("Omega", "Nu", 9);
        graph2.addEdge("Omega", "Omnicron", 10);
        graph2.addEdge("Sigma", "omnicron", 9);
        graph2.addEdge("Sigma", "Xi", 5);
        graph2.addEdge("Kappa", "Theta", 3);
        graph2.addEdge("Kappa", "Mu", 9);
        graph2.addEdge("Kappa", "Nu", 7);
        graph2.addEdge("Kappa", "Iota", 5);
        graph2.addEdge("Epsilon", "Delta", 4);
        graph2.addEdge("Epsilon", "Theta", 5);
        graph2.addEdge("Epsilon", "Zeta", 9);
        graph2.addEdge("Zeta", "Epsilon", 9);
        graph2.addEdge("Zeta", "Gamma", 8);
        graph2.addEdge("Zeta", "Iota", 10);
        graph2.addEdge("Iota", "Zeta", 10);
        graph2.addEdge("Iota", "Theta", 4);
        graph2.addEdge("Iota", "Kappa", 5);
        graph2.addEdge("Iota", "Theta", 4);

        System.out.println("\n================================================");
        graph2.dijkstra("Mu");
        graph2.printPaths("Mu");

    
    }
}

        
        
